# Generated by Django 3.1.2 on 2020-12-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagestonames',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lang', to='parliament_api.languages'),
        ),
        migrations.AlterField(
            model_name='partiestonames',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='part', to='parliament_api.parties'),
        ),
        migrations.AlterField(
            model_name='professionstonames',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prof', to='parliament_api.professions'),
        ),
    ]
